### ISSUE TITLE
Needs more commits

### ISSUE THREAD

**Issue by marcusstenbeck** [dallaspersson/enigma-simulator#1]
## Issue

Lack of commits.
## How to reproduce

Visit [commit history](https://github.com/dallaspersson/enigma-simulator/commits/master) and observe number of commits.
## Expected

More commits

**Comment by marcusstenbeck** [comment]
🍺🍺🍺🍺🍺🍺

**Comment by dallaspersson** [comment]
I see what you mean. ;) 
Have some uncommitted code on my laptop. Will fix this issue in the next coming days.

**Comment by marcusstenbeck** [comment]
"It works locally!!"

😅🍻

**Comment by dallaspersson** [comment]
Haha yeah thats right. I will push up some code in the coming days. Thanks for showing interest! :smiley:

**Comment by marcusstenbeck** [comment]
Sweet! I'm waiting on it!
